version: '3'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8000
    volumes:
      - .:/home/python/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: loja
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: superuser
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
